### ISSUE TITLE
RAM issues when indexing massive Events

### ISSUE THREAD

**Issue by afandian** [CrossRef/event-data-query#36]
Some very large accidental Events have crept in (by mistake), e.g. http://bus.eventdata.crossref.org/events/56e57c42-5b47-4f0d-9782-0c8bbabcd1ed

These are ~ 700x the expected size. They have caused JVM Heap issues, as Events are bundled up into batches of 1000 on ingestion into Elastic Search for efficiency. 

Solution is an emergency circuit-breaker of 10,000 bytes per message (they are usually around 1 or 2 kb).

**Comment by afandian** [comment]
Stack trace:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space, compiling:(/tmp/form-init8494498489535884362.clj:1:73)
at clojure.lang.Compiler.load(Compiler.java:7391)
at clojure.lang.Compiler.loadFile(Compiler.java:7317)
at clojure.main$load_script.invokeStatic(main.clj:275)
at clojure.main$init_opt.invokeStatic(main.clj:277)
at clojure.main$init_opt.invoke(main.clj:277)
at clojure.main$initialize.invokeStatic(main.clj:308)
at clojure.main$null_opt.invokeStatic(main.clj:342)
at clojure.main$null_opt.invoke(main.clj:339)
at clojure.main$main.invokeStatic(main.clj:421)
at clojure.main$main.doInvoke(main.clj:384)
at clojure.lang.RestFn.invoke(RestFn.java:421)
at clojure.lang.Var.invoke(Var.java:383)
at clojure.lang.AFn.applyToHelper(AFn.java:156)
at clojure.lang.Var.applyTo(Var.java:700)
at clojure.main.main(main.java:37)
Caused by: java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOf(Arrays.java:3332)
at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
at java.lang.StringBuilder.append(StringBuilder.java:136)
at qbits.spandex$chunks__GT_body$fn__9995.invoke(spandex.clj:394)
at clojure.core$run_BANG_$fn__7276.invoke(core.clj:7393)
at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
at clojure.core.protocols$fn__6750.invokeStatic(protocols.clj:136)
at clojure.core.protocols$fn__6750.invoke(protocols.clj:124)
at clojure.core.protocols$fn__6710$G__6705__6719.invoke(protocols.clj:19)
at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
at clojure.core$reduce.invokeStatic(core.clj:6545)
at clojure.core$run_BANG_.invokeStatic(core.clj:7388)
at clojure.core$run_BANG_.invoke(core.clj:7388)
at qbits.spandex$chunks__GT_body.invokeStatic(spandex.clj:394)
at qbits.spandex$chunks__GT_body.invoke(spandex.clj:388)
at event_data_query.elastic$insert_events$fn__14563.invoke(elastic.clj:414)
at clojure.lang.AFn.applyToHelper(AFn.java:152)
at clojure.lang.AFn.applyTo(AFn.java:144)
at clojure.core$apply.invokeStatic(core.clj:646)
at clojure.core$apply.invoke(core.clj:641)
at robert.bruce$try_try_again$fn__13130.invoke(bruce.clj:167)
at robert.bruce$retry$fn__13119.invoke(bruce.clj:137)
at robert.bruce$retry.invokeStatic(bruce.clj:136)
at robert.bruce$retry.invoke(bruce.clj:127)
at clojure.lang.AFn.applyToHelper(AFn.java:156)
at clojure.lang.AFn.applyTo(AFn.java:144)
at clojure.core$apply.invokeStatic(core.clj:646)
19-03-18 22:19:42 c858b6c06be4 INFO [org.apache.kafka.clients.consumer.internals.AbstractCoordinator:432] - (Re-)joining group 2018_07_31_query-input
19-03-18 22:19:45 c858b6c06be4 INFO [org.apache.kafka.clients.consumer.internals.AbstractCoordinator:399] - Successfully joined group 2018_07_31_query-input with generation 50
19-03-18 22:19:45 c858b6c06be4 INFO [org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:262] - Setting newly assigned partitions [bus-event-output-0] for group 2018_07_31_query-input
19-03-18 22:19:45 c858b6c06be4 INFO [event-data-query.ingest:288] - Polling...
19-03-18 22:19:45 c858b6c06be4 INFO [event-data-query.ingest:288] - Polling...
19-03-18 22:19:45 c858b6c06be4 INFO [event-data-query.ingest:288] - Polling...
19-03-18 22:19:45 c858b6c06be4 INFO [event-data-query.ingest:288] - Polling...
19-03-18 22:19:45 c858b6c06be4 INFO [event-data-query.ingest:288] - Polling...
19-03-18 22:19:46 c858b6c06be4 INFO [event-data-query.ingest:288] - Polling...
19-03-18 22:19:47 c858b6c06be4 INFO [event-data-query.ingest:288] - Polling...
19-03-18 22:19:47 c858b6c06be4 INFO [event-data-query.ingest:288] - Polling...
19-03-18 22:19:47 c858b6c06be4 INFO [event-data-query.ingest:288] - Polling...
19-03-18 22:19:47 c858b6c06be4 INFO [event-data-query.ingest:288] - Polling...
19-03-18 22:19:47 c858b6c06be4 INFO [event-data-query.ingest:288] - Polling...




and again


12:05:12
19-03-21 12:05:12 0a73ba53e4b0 ERROR [event-data-query.work-cache:288] - #error {
:cause SSL peer shut down incorrectly
:via
[{:type java.io.EOFException
:message SSL peer shut down incorrectly
:at [sun.security.ssl.InputRecord read InputRecord.java 505]}]
:trace
[[sun.security.ssl.InputRecord read InputRecord.java 505]
[sun.security.ssl.SSLSocketImpl readRecord SSLSocketImpl.java 973]
[sun.security.ssl.SSLSocketImpl performInitialHandshake SSLSocketImpl.java 1375]
[sun.security.ssl.SSLSocketImpl startHandshake SSLSocketImpl.java 1403]
[sun.security.ssl.SSLSocketImpl startHandshake SSLSocketImpl.java 1387]
[org.apache.http.conn.ssl.SSLConnectionSocketFactory createLayeredSocket SSLConnectionSocketFactory.java 394]
[org.apache.http.conn.ssl.SSLConnectionSocketFactory connectSocket SSLConnectionSocketFactory.java 353]
[org.apache.http.impl.conn.DefaultHttpClientConnectionOperator connect DefaultHttpClientConnectionOperator.java 141]
[org.apache.http.impl.conn.BasicHttpClientConnectionManager connect BasicHttpClientConnectionManager.java 338]
[org.apache.http.impl.execchain.MainClientExec establishRoute MainClientExec.java 380]
[org.apache.http.impl.execchain.MainClientExec execute MainClientExec.java 236]
[org.apache.http.impl.execchain.ProtocolExec execute ProtocolExec.java 184]
[org.apache.http.impl.execchain.RetryExec execute RetryExec.java 88]
[org.apache.http.impl.execchain.RedirectExec execute RedirectExec.java 110]
[org.apache.http.impl.client.InternalHttpClient doExecute InternalHttpClient.java 184]
[org.apache.http.impl.client.CloseableHttpClient execute CloseableHttpClient.java 82]
[clj_http.core$request invokeStatic core.clj 387]
[clj_http.core$request invoke core.clj 321]
[clj_http.core$request invokeStatic core.clj 322]
[clj_http.core$request invoke core.clj 321]
[clojure.lang.Var invoke Var.java 379]
[clj_http.client$wrap_request_timing$fn__12485 invoke client.clj 1013]
[clj_http.client$wrap_async_pooling$fn__12493 invoke client.clj 1046]
[clj_http.headers$wrap_header_map$fn__11584 invoke headers.clj 147]
[clj_http.client$wrap_query_params$fn__12379 invoke client.clj 773]
[clj_http.client$wrap_basic_auth$fn__12385 invoke client.clj 796]
[clj_http.client$wrap_oauth$fn__12390 invoke client.clj 813]
[clj_http.client$wrap_user_info$fn__12397 invoke client.clj 833]
[clj_http.client$wrap_url$fn__12467 invoke client.clj 965]
[clj_http.client$wrap_redirects$fn__12139 invoke client.clj 344]
[clj_http.client$wrap_decompression$fn__12165 invoke client.clj 397]
[clj_http.client$wrap_input_coercion$fn__12307 invoke client.clj 593]
[clj_http.client$wrap_additional_header_parsing$fn__12332 invoke client.clj 648]
[clj_http.client$wrap_output_coercion$fn__12294 invoke client.clj 537]
[clj_http.client$wrap_exceptions$fn__12115 invoke client.clj 232]
[clj_http.client$wrap_accept$fn__12347 invoke client.clj 691]
[clj_http.client$wrap_accept_encoding$fn__12354 invoke client.clj 713]
[clj_http.client$wrap_content_type$fn__12341 invoke client.clj 674]
[clj_http.client$wrap_form_params$fn__12444 invoke client.clj 915]
[clj_http.client$wrap_nested_params$fn__12462 invoke client.clj 950]
[clj_http.client$wrap_method$fn__12402 invoke client.clj 849]
[clj_http.cookies$wrap_cookies$fn__10529 invoke cookies.clj 131]
[clj_http.links$wrap_links$fn__11840 invoke links.clj 63]
[clj_http.client$wrap_unknown_host$fn__12470 invoke client.clj 976]
[clj_http.client$request_STAR_ invokeStatic client.clj 1149]
[clj_http.client$request_STAR_ invoke client.clj 1142]
[clj_http.client$get invokeStatic client.clj 1155]
[clj_http.client$get doInvoke client.clj 1151]
[clojure.lang.RestFn invoke RestFn.java 410]
[event_data_query.work_cache$get_ra_api invokeStatic work_cache.clj 100]
[event_data_query.work_cache$get_ra_api invoke work_cache.clj 89]
[event_data_query.work_cache$get_work_api invokeStatic work_cache.clj 117]
[event_data_query.work_cache$get_work_api invoke work_cache.clj 111]
[event_data_query.work_cache$get_for_dois$fn__13227 invoke work_cache.clj 162]
[clojure.core$map$fn__4785 invoke core.clj 2644]
[clojure.lang.LazySeq sval LazySeq.java 40]
[clojure.lang.LazySeq seq LazySeq.java 49]
[clojure.lang.RT seq RT.java 521]
[clojure.core$seq__4357 invokeStatic core.clj 137]
[clojure.core$seq__4357 invoke core.clj 137]
[event_data_query.work_cache$get_for_dois invokeStatic work_cache.clj 164]
[event_data_query.work_cache$get_for_dois invoke work_cache.clj 144]
[event_data_query.elastic$event__GT_document invokeStatic elastic.clj 298]
[event_data_query.elastic$event__GT_document invoke elastic.clj 259]
[clojure.lang.AFn applyToHelper AFn.java 154]
[clojure.lang.AFn applyTo AFn.java 144]
[clojure.core$apply invokeStatic core.clj 646]
[clojure.core$apply invoke core.clj 641]
[com.climate.claypoole$pmap_core$start_task__14354$fn__14355 invoke claypoole.clj 323]
[clojure.lang.AFn applyToHelper AFn.java 152]
[clojure.lang.AFn applyTo AFn.java 144]
[clojure.lang.AFunction$1 doInvoke AFunction.java 29]
[clojure.lang.RestFn invoke RestFn.java 397]
[com.climate.claypoole.impl$binding_conveyor_fn$fn__14222 invoke impl.clj 46]
[clojure.lang.AFn applyToHelper AFn.java 152]
[clojure.lang.AFn applyTo AFn.java 144]
[clojure.lang.AFunction$1 doInvoke AFunction.java 29]
[clojure.lang.RestFn invoke RestFn.java 397]
[clojure.lang.AFn call AFn.java 18]
[java.util.concurrent.FutureTask run FutureTask.java 266]
[java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask access$201 ScheduledThreadPoolExecutor.java 180]
[java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask run ScheduledThreadPoolExecutor.java 293]
[java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
[java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
[java.lang.Thread run Thread.java 745]]}

12:05:12
19-03-21 12:05:12 0a73ba53





[java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask run ScheduledThreadPoolExecutor.java 293]
[java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
[java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
[java.lang.Thread run Thread.java 745]]}
19-03-21 12:05:14 0a73ba53e4b0 ERROR [event-data-query.work-cache:288] - #error {
:cause SSL peer shut down incorrectly
:via
[{:type java.io.EOFException
:message SSL peer shut down incorrectly
:at [sun.security.ssl.InputRecord read InputRecord.java 505]}]
:trace
[[sun.security.ssl.InputRecord read InputRecord.java 505]
[sun.security.ssl.SSLSocketImpl readRecord SSLSocketImpl.java 973]
[sun.security.ssl.SSLSocketImpl performInitialHandshake SSLSocketImpl.java 1375]
[sun.security.ssl.SSLSocketImpl startHandshake SSLSocketImpl.java 1403]
[sun.security.ssl.SSLSocketImpl startHandshake SSLSocketImpl.java 1387]
[org.apache.http.conn.ssl.SSLConnectionSocketFactory createLayeredSocket SSLConnectionSocketFactory.java 394]
[org.apache.http.conn.ssl.SSLConnectionSocketFactory connectSocket SSLConnectionSocketFactory.java 353]
[org.apache.http.impl.conn.DefaultHttpClientConnectionOperator connect DefaultHttpClientConnectionOperator.java 141]
[org.apache.http.impl.conn.BasicHttpClientConnectionManager connect BasicHttpClientConnectionManager.java 338]
[org.apache.http.impl.execchain.MainClientExec establishRoute MainClientExec.java 380]
[org.apache.http.impl.execchain.MainClientExec execute MainClientExec.java 236]
[org.apache.http.impl.execchain.ProtocolExec execute ProtocolExec.java 184]
[org.apache.http.impl.execchain.RetryExec execute RetryExec.java 88]
[org.apache.http.impl.execchain.RedirectExec execute RedirectExec.java 110]
[org.apache.http.impl.client.InternalHttpClient doExecute InternalHttpClient.java 184]
[org.apache.http.impl.client.CloseableHttpClient execute CloseableHttpClient.java 82]
[clj_http.core$request invokeStatic core.clj 387]
[clj_http.core$request invoke core.clj 321]
[clj_http.core$request invokeStatic core.clj 322]
[clj_http.core$request invoke core.clj 321]
[clojure.lang.Var invoke Var.java 379]
[clj_http.client$wrap_request_timing$fn__12485 invoke client.clj 1013]
[clj_http.client$wrap_async_pooling$fn__12493 invoke client.clj 1046]
[clj_http.headers$wrap_header_map$fn__11584 invoke headers.clj 147]
[clj_http.client$wrap_query_params$fn__12379 invoke client.clj 773]
[clj_http.client$wrap_basic_auth$fn__12385 invoke client.clj 796]
[clj_http.client$wrap_oauth$fn__12390 invoke client.clj 813]
[clj_http.client$wrap_user_info$fn__12397 invoke client.clj 833]
[clj_http.client$wrap_url$fn__12467 invoke client.clj 965]
[clj_http.client$wrap_redirects$fn__12139 invoke client.clj 344]
[clj_http.client$wrap_decompression$fn__12165 invoke client.clj 397]
[clj_http.client$wrap_input_coercion$fn__12307 invoke client.clj 593]
[clj_http.client$wrap_additional_header_parsing$fn__12332 invoke client.clj 648]
[clj_http.client$wrap_output_coercion$fn__12294 invoke client.clj 537]
[clj_http.client$wrap_exceptions$fn__12115 invoke client.clj 232]
[clj_http.client$wrap_accept$fn__12347 invoke client.clj 691]
[clj_http.client$wrap_accept_encoding$fn__12354 invoke client.clj 713]
[clj_http.client$wrap_content_type$fn__12341 invoke client.clj 674]
[clj_http.client$wrap_form_params$fn__12444 invoke client.clj 915]
[clj_http.client$wrap_nested_params$fn__12462 invoke client.clj 950]
[clj_http.client$wrap_method$fn__12402 invoke client.clj 849]
[clj_http.cookies$wrap_cookies$fn__10529 invoke cookies.clj 131]
[clj_http.links$wrap_links$fn__11840 invoke links.clj 63]
[clj_http.client$wrap_unknown_host$fn__12470 invoke client.clj 976]
[clj_http.client$request_STAR_ invokeStatic client.clj 1149]
[clj_http.client$request_STAR_ invoke client.clj 1142]
[clj_http.client$get invokeStatic client.clj 1155]
[clj_http.client$get doInvoke client.clj 1151]
[clojure.lang.RestFn invoke RestFn.java 410]
[event_data_query.work_cache$get_ra_api invokeStatic work_cache.clj 100]
[event_data_query.work_cache$get_ra_api invoke work_cache.clj 89]
[event_data_query.work_cache$get_work_api invokeStatic work_cache.clj 117]
[event_data_query.work_cache$get_work_api invoke work_cache.clj 111]
[event_data_query.work_cache$get_for_dois$fn__13227 invoke work_cache.clj 162]
[clojure.core$map$fn__4785 invoke core.clj 2644]
[clojure.lang.LazySeq sval LazySeq.java 40]
[clojure.lang.LazySeq seq LazySeq.java 49]
[clojure.lang.RT seq RT.java 521]
[clojure.core$seq__4357 invokeStatic core.clj 137]
[clojure.core$seq__4357 invoke core.clj 137]
[event_data_query.work_cache$get_for_dois invokeStatic work_cache.clj 164]
[event_data_query.work_cache$get_for_dois invoke work_cache.clj 144]
[event_data_query.elastic$event__GT_document invokeStatic elastic.clj 298]
[event_data_query.elastic$event__GT_document invoke elastic.clj 259]
[clojure.lang.AFn applyToHelper AFn.java 154]
[clojure.lang.AFn applyTo AFn.java 144]
[clojure.core$apply invokeStatic core.clj 646]
[clojure.core$apply invoke core.clj 641]
[com.climate.claypoole$pmap_core$start_task__14354$fn__14355 invoke claypoole.clj 323]
[clojure.lang.AFn applyToHelper AFn.java 152]
[clojure.lang.AFn applyTo AFn.java 144]
[clojure.lang.AFunction$1 doInvoke AFunction.java 29]
[clojure.lang.RestFn invoke RestFn.java 397]
[com.climate.claypoole.impl$binding_conveyor_fn$fn__14222 invoke impl.clj 46]
[clojure.lang.AFn applyToHelper AFn.java 152]
[clojure.lang.AFn applyTo AFn.java 144]
[clojure.lang.AFunction$1 doInvoke AFunction.java 29]
[clojure.lang.RestFn invoke RestFn.java 397]
[clojure.lang.AFn call AFn.java 18]
[java.util.concurrent.FutureTask run FutureTask.java 266]
[java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask access$201 ScheduledThreadPoolExecutor.java 180]
[java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask run ScheduledThreadPoolExecutor.java 293]
[java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
[java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
[java.lang.Thread run Thread.java 745]]}
19-03-21 12:05:14 0a73ba53e4b0 ERROR [event-data-query.work-cache:288] - #error {
:cause SSL peer shut down incorrectly
:via
[{:type java.io.EOFException
:message SSL peer shut down incorrectly
:at [sun.security.ssl.InputRecord read InputRecord.java 505]}]
:trace
[[sun.security.ssl.InputRecord read InputRecord.java 505]
[sun.security.ssl.SSLSocketImpl readRecord SSLSocketImpl.java 973]
[sun.security.ssl.SSLSocketImpl performInitialHandshake SSLSocketImpl.java 1375]
[sun.security.ssl.SSLSocketImpl startHandshake SSLSocketImpl.java 1403]
[sun.security.ssl.SSLSocketImpl startHandshake SSLSocketImpl.java 1387]
[org.apache.http.conn.ssl.SSLConnectionSocketFactory createLayeredSocket SSLConnectionSocketFactory.java 394]
[org.apache.http.conn.ssl.SSLConnectionSocketFactory connectSocket SSLConnectionSocketFactory.java 353]
[org.apache.http.impl.conn.DefaultHttpClientConnectionOperator connect DefaultHttpClientConnectionOperator.java 141]
[org.apache.http.impl.conn.BasicHttpClientConnectionManager connect BasicHttpClientConnectionManager.java 338]
[org.apache.http.impl.execchain.MainClientExec establishRoute MainClientExec.java 380]
[org.apache.http.impl.execchain.MainClientExec execute MainClientExec.java 236]
[org.apache.http.impl.execchain.ProtocolExec execute ProtocolExec.java 184]
[org.apache.http.impl.execchain.RetryExec execute RetryExec.java 88]
[org.apache.http.impl.execchain.RedirectExec execute RedirectExec.java 110]
[org.apache.http.impl.client.InternalHttpClient doExecute InternalHttpClient.java 184]
[org.apache.http.impl.client.CloseableHttpClient execute CloseableHttpClient.java 82]
[clj_http.core$request invokeStatic core.clj 387]
[clj_http.core$request invoke core.clj 321]
[clj_http.core$request invokeStatic core.clj 322]
[clj_http.core$request invoke core.clj 321]
[clojure.lang.Var invoke Var.java 379]
[clj_http.client$wrap_request_timing$fn__12485 invoke client.clj 1013]
[clj_http.client$wrap_async_pooling$fn__12493 invoke client.clj 1046]
[clj_http.headers$wrap_header_map$fn__11584 invoke headers.clj 147]
[clj_http.client$wrap_query_params$fn__12379 invoke client.clj 773]
[clj_http.client$wrap_basic_auth$fn__12385 invoke client.clj 796]
[clj_http.client$wrap_oauth$fn__12390 invoke client.clj 813]
[clj_http.client$wrap_user_info$fn__12397 invoke client.clj 833]
[clj_http.client$wrap_url$fn__12467 invoke client.clj 965]
[clj_http.client$wrap_redirects$fn__12139 invoke client.clj 344]
[clj_http.client$wrap_decompression$fn__12165 invoke client.clj 397]
[clj_http.client$wrap_input_coercion$fn__12307 invoke client.clj 593]
[clj_http.client$wrap_additional_header_parsing$fn__12332 invoke client.clj 648]
[clj_http.client$wrap_output_coercion$fn__12294 invoke client.clj 537]
[clj_http.client$wrap_exceptions$fn__12115 invoke client.clj 232]
[clj_http.client$wrap_accept$fn__12347 invoke client.clj 691]
[clj_http.client$wrap_accept_encoding$fn__12354 invoke client.clj 713]
[clj_http.client$wrap_content_type$fn__12341 invoke client.clj 674]
[clj_http.client$wrap_form_params$fn__12444 invoke client.clj 915]
[clj_http.client$wrap_nested_params$fn__12462 invoke client.clj 950]
[clj_http.client$wrap_method$fn__12402 invoke client.clj 849]
[clj_http.cookies$wrap_cookies$fn__10529 invoke cookies.clj 131]
[clj_http.links$wrap_links$fn__11840 invoke links.clj 63]
[clj_http.client$wrap_unknown_host$fn__12470 invoke client.clj 976]
[clj_http.client$request_STAR_ invokeStatic client.clj 1149]
[clj_http.client$request_STAR_ invoke client.clj 1142]
[clj_http.client$get invokeStatic client.clj 1155]
[clj_http.client$get doInvoke client.clj 1151]
[clojure.lang.RestFn invoke RestFn.java 410]
[event_data_query.work_cache$get_ra_api invokeStatic work_cache.clj 100]
[event_data_query.work_cache$get_ra_api invoke work_cache.clj 89]
[event_data_query.work_cache$get_work_api invokeStatic work_cache.clj 117]
[event_data_query.work_cache$get_work_api invoke work_cache.clj 111]
[event_data_query.work_cache$get_for_dois$fn__13227 invoke work_cache.clj 162]
[clojure.core$map$fn__4785 invoke core.clj 2644]
[clojure.lang.LazySeq sval LazySeq.java 40]
[clojure.lang.LazySeq seq LazySeq.java 49]
[clojure.lang.RT seq RT.java 521]
[clojure.core$seq__4357 invokeStatic core.clj 137]
[clojure.core$seq__4357 invoke core.clj 137]
[event_data_query.work_cache$get_for_dois invokeStatic work_cache.clj 164]
[event_data_query.work_cache$get_for_dois invoke work_cache.clj 144]
[event_data_query.elastic$event__GT_document invokeStatic elastic.clj 298]
[event_data_query.elastic$event__GT_document invoke elastic.clj 259]
[clojure.lang.AFn applyToHelper AFn.java 154]
[clojure.lang.AFn applyTo AFn.java 144]
[clojure.core$apply invokeStatic core.clj 646]
[clojure.core$apply invoke core.clj 641]
[com.climate.claypoole$pmap_core$start_task__14354$fn__14355 invoke claypoole.clj 323]
[clojure.lang.AFn applyToHelper AFn.java 152]
[clojure.lang.AFn applyTo AFn.java 144]
[clojure.lang.AFunction$1 doInvoke AFunction.java 29]
[clojure.lang.RestFn invoke RestFn.java 397]
[com.climate.claypoole.impl$binding_conveyor_fn$fn__14222 invoke impl.clj 46]
[clojure.lang.AFn applyToHelper AFn.java 152]
[clojure.lang.AFn applyTo AFn.java 144]
[clojure.lang.AFunction$1 doInvoke AFunction.java 29]
[clojure.lang.RestFn invoke RestFn.java 397]
[clojure.lang.AFn call AFn.java 18]
[java.util.concurrent.FutureTask run FutureTask.java 266]
[java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask access$201 ScheduledThreadPoolExecutor.java 180]
[java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask run ScheduledThreadPoolExecutor.java 293]
[java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
[java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
[java.lang.Thread run Thread.java 745]]}
```
