### ISSUE TITLE
OOM on parameter parsing

### ISSUE THREAD

**Issue by afandian** [CrossRef/event-data-query#6]
Didn't log the supplied value. 
```
Mon Jun 05 14:43:04 UTC 2017 [worker-2] ERROR - GET /events
java.lang.OutOfMemoryError: GC overhead limit exceeded
 at clojure.lang.Tuple.create(Tuple.java:26)
 at event_data_query.parameters$read_ident.invokeStatic(parameters.clj:18)
 at event_data_query.parameters$read_ident.invoke(parameters.clj:15)
 at event_data_query.parameters$read_token.invokeStatic(parameters.clj:66)
 at event_data_query.parameters$read_token.invoke(parameters.clj:56)
 at event_data_query.parameters$scan.invokeStatic(parameters.clj:72)
 at event_data_query.parameters$scan.invoke(parameters.clj:68)
 at event_data_query.parameters$parse.invokeStatic(parameters.clj:80)
 at event_data_query.parameters$parse.invoke(parameters.clj:76)
 at event_data_query.server$events$fn__18554$fn__18555.invoke(server.clj:114)
 at liberator.core$decide.invokeStatic(core.clj:81)
 at liberator.core$decide.invoke(core.clj:73)
 at liberator.core$malformed_QMARK_.invokeStatic(core.clj:479)
 at liberator.core$malformed_QMARK_.invoke(core.clj:479)
 at liberator.core$decide.invokeStatic(core.clj:86)
 at liberator.core$decide.invoke(core.clj:73)
 at liberator.core$method_allowed_QMARK_.invokeStatic(core.clj:482)
 at liberator.core$method_allowed_QMARK_.invoke(core.clj:482)
 at liberator.core$decide.invokeStatic(core.clj:86)
 at liberator.core$decide.invoke(core.clj:73)
 at liberator.core$uri_too_long_QMARK_.invokeStatic(core.clj:485)
 at liberator.core$uri_too_long_QMARK_.invoke(core.clj:485)
 at liberator.core$decide.invokeStatic(core.clj:86)
 at liberator.core$decide.invoke(core.clj:73)
 at liberator.core$known_method_QMARK_.invokeStatic(core.clj:488)
 at liberator.core$known_method_QMARK_.invoke(core.clj:488)
 at liberator.core$decide.invokeStatic(core.clj:86)
 at liberator.core$decide.invoke(core.clj:73)
 at liberator.core$service_available_QMARK_.invokeStatic(core.clj:491)
 at liberator.core$service_available_QMARK_.invoke(core.clj:491)
 at liberator.core$decide.invokeStatic(core.clj:86)
 at liberator.core$decide.invoke(core.clj:73)
```

**Comment by afandian** [comment]
Logging now in place to catch this if it happens again. Closing until it happens.
